# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '16.x'
        displayName: 'Install Node.js 16.x'

      - script: |
          npm install -g @angular/cli
          npm install
          ng build --configuration=production
        displayName: 'npm install and build'
        workingDirectory: '$(Build.SourcesDirectory)' 

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/side-bar'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'

- stage: Development
  displayName: 'Deploy to Development'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentDevelopment
    pool:
      vmImage: 'ubuntu-latest'
    environment: Development
    strategy:
      runOnce:
        deploy:
          steps:

          - task: AzureWebApp@1
            displayName: 'Deploy App Service'
            inputs:
              azureSubscription: 'Azure for Students (551a22a1-42dc-475a-afec-b638f6f4ac13)'
              appType: 'webAppLinux'
              appName: 'inscriptionsUptc'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'NODE|16-lts'

- stage: Acceptance
  dependsOn: [ Development ]
  displayName: 'Deploy to Acceptance'
  jobs:
    - job: DeployToAcceptance
      displayName: 'DeployAcceptance'
      steps:
      - script: echo Deploying to Acceptance
        displayName: 'Validate deployment'
      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'
          mergeTestResults: true
        condition: always()

- stage: Production
  dependsOn: [ Acceptance ]
  displayName: 'Deploy to Production'
  jobs:
    - deployment: DeployProduction
      pool:
        vmImage: 'ubuntu-latest'
      environment: Production
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo Deploying to Production
              displayName: 'Validate deployment'
            - task: PublishTestResults@2
              displayName: 'Publish test results'
              inputs:
                testResultsFormat: 'JUnit'
                testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'
                mergeTestResults: true
              condition: always()